### ISSUE TITLE
nose-machineout

### ISSUE THREAD

**Issue by metaswirl** [lambdalisue/nose.vim#4]
It looks like github.com/nvie/nose-machineout.git is no longer available. 

It worked for me using your version of nose-machineout. Additionally, if you would add the following lines to your version of nose-machineout, it would work under python as well.

```
try:
    unicode = unicode
except NameError:
    # 'unicode' is undefined, must be Python 3
    str = str
    unicode = str
    bytes = bytes
    basestring = (str,bytes)
else:
    # 'unicode' exists, must be Python 2
    str = str
    unicode = unicode
    bytes = str
    basestring = basestring
```
(from:) https://github.com/oxplot/fysom/issues/1

I suspect only the basestring part of the clause is really necessary.

Thank you again for this great tool!

**Comment by lambdalisue** [comment]
I just simply start `nose-machineout2` https://github.com/lambdalisue/nose-machineout2

**Comment by lambdalisue** [comment]
Now you can get it from PyPI as

```
$ pip install nose_machineout2
```
